#!/bin/bash

k=2
#k=4
#k=6
#k=8
#k=10
start=60
end=100
for ((i=$start; i<=$end; i++)); do

	mkdir SP$k

	#mkdir /your/folder/SP_v26_Data/SP$k
	mkdir /mnt/data/SP_v26_Data/SP$k

	cp SP_Template SP$k/SP$k\_$i.foma
	sed -i "s/<LEN>/$i/g" SP$k/SP$k\_$i.foma

	if [ $k = 2 ]
	then
		sed -i "s/<FORBIDDEN>/a b | b c | c d | d e | e f | f g/g" SP$k/SP$k\_$i.foma
	elif [ $k = 4 ]
	then
		sed -i "s/<FORBIDDEN>/a b b a | b c c b | c d d c | d e e d | e f f e | f g g f/g" SP$k/SP$k\_$i.foma
	elif [ $k = 6 ]
	then
		sed -i "s/<FORBIDDEN>/a b b a a b | b c c b b c | c d d c c d | d e e d d e | e f f e e f | f g g f f g/g" SP$k/SP$k\_$i.foma

	elif [ $k = 8 ]
	then
		sed -i "s/<FORBIDDEN>/a b b a a b b a | b c c b b c c b | c d d c c d d c | d e e d d e e d | e f f e e f f e | f g g f f g g f | f f h h i i k k/g" SP$k/SP$k\_$i.foma
	elif [ $k = 10 ]
	then
		sed -i "s/<FORBIDDEN>/a b b a a b b a a b | b c c b b c c b b c | c d d c c d d c c d | d e e d d e e d d e | e f f e e f f e e f | f g g f f g g f f g/g" SP$k/SP$k\_$i.foma

	elif [ $k = 12 ]
	then
		sed -i "s/<FORBIDDEN>/a b b a a b b a a b b a | b c c b b c c b b c c b | c d d c c d d c c d d c | d e e d d e e d d e e d | e f f e e f f e e f f e | f g g f f g g f f g g f/g" SP$k/SP$k\_$i.foma
	elif [ $k = 16 ]
	then
		sed -i "s/<FORBIDDEN>/a b b a a b b a a b b a a b b a | b c c b b c c b b c c b b c c b | c d d c c d d c c d d c c d d c | d e e d d e e d d e e d d e e d | e f f e e f f e e f f e e f f e | f g g f f g g f f g g f f g g f | g h h g g h h g g h h g g h h g | h i i h h i i h h i i h h i i h | i j j i i j j i i j j i i j j i | j k k j j k k j j k k j j k k j | k l l k k l l k k l l k k l l k | l m m l l m m l l m m l l m m l | m n n m m n n m m n n m m n n m | n o o n n o o n n o o n n o o n | o p p o o p p o o p p o o p p o | p q q p p q q p p q q p p q q p | q r r q q r r q q r r q q r r q | r s s r r s s r r s s r r s s r/g" SP$k/SP$k\_$i.foma
	fi

	echo "Processing file: "SP$k/SP$k\_$i.foma

	# Replace /mnt/data/SP_v26_Data with your own path
	touch /mnt/data/SP_v26_Data/SP$k/SP$k\_$i.dat
	foma -f SP$k/SP$k\_$i.foma > /mnt/data/SP_v26_Data/SP$k/SP$k\_$i.dat
done
